const fs = require('fs');

const rewriteTail = (file, matchStr, correctTail) => {
    let content = fs.readFileSync('app/studio/components/' + file, 'utf8');
    let idx = content.indexOf(matchStr);
    if (idx === -1) {
        console.log('Could not find match in ' + file);
        return;
    }
    let newContent = content.substring(0, idx) + correctTail;
    fs.writeFileSync('app/studio/components/' + file, newContent);
    console.log('Fixed ' + file);
}

// 1. ChallengeCardGenerator.tsx
rewriteTail('ChallengeCardGenerator.tsx',
'                       <div className="font-bold text-[#secondary-lime] text-sm uppercase">{formData.reward}app/studio/components/PaceBandGenerator.tsx',
`                       <div className="font-bold text-[#secondary-lime] text-sm uppercase">{formData.reward}app/studio/components/PaceBandGenerator.tsx
                      app/studio/components/PaceBandGenerator.tsx
                 </>
               )}
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (
             <SharedTemplates template={template} formData={formData} componentName="ChallengeCardGenerator"  />
           )}
      app/studio/components/PaceBandGenerator.tsx
    app/studio/components/PaceBandGenerator.tsx
  );
}
`);

// 2. FuelingPlanGenerator.tsx
rewriteTail('FuelingPlanGenerator.tsx',
'                       Manual plan only. Not medical or nutrition advice.<br/>{typeof window !== \'undefined\' && window.localStorage.getItem(\'runcard-watermark\') === \'off\' ? \'\' : \'RunCard Studio\'}</p>',
`                       Manual plan only. Not medical or nutrition advice.<br/>{typeof window !== 'undefined' && window.localStorage.getItem('runcard-watermark') === 'off' ? '' : 'RunCard Studio'}</p>
                   app/studio/components/PaceBandGenerator.tsx
                 </>
               )}
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (
             <SharedTemplates template={template} formData={formData} componentName="FuelingPlanGenerator"  />
           )}
      app/studio/components/PaceBandGenerator.tsx
    app/studio/components/PaceBandGenerator.tsx
  );
}
`);

// 3. GoalCardGenerator.tsx
rewriteTail('GoalCardGenerator.tsx',
'<div className="absolute bottom-4 right-10 text-[8px] font-mono tracking-widest text-gray-300 uppercase">{typeof window !== \'undefined\' && window.localStorage.getItem(\'runcard-watermark\') === \'off\' ? \'\' : \'RunCard Studio\'}app/studio/components/PaceBandGenerator.tsx',
`<div className="absolute bottom-4 right-10 text-[8px] font-mono tracking-widest text-gray-300 uppercase">{typeof window !== 'undefined' && window.localStorage.getItem('runcard-watermark') === 'off' ? '' : 'RunCard Studio'}app/studio/components/PaceBandGenerator.tsx
                 </>
               )}
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (
             <SharedTemplates template={template} formData={formData} componentName="GoalCardGenerator"  />
           )}
      app/studio/components/PaceBandGenerator.tsx
    app/studio/components/PaceBandGenerator.tsx
  );
}
`);

// 4. PaceBandGenerator.tsx
rewriteTail('PaceBandGenerator.tsx',
'                   <div className="mt-16 text-center text-[10px] font-mono uppercase tracking-[0.2em] opacity-40 pt-6 border-t border-dashed border-gray-300">',
`                   <div className="mt-16 text-center text-[10px] font-mono uppercase tracking-[0.2em] opacity-40 pt-6 border-t border-dashed border-gray-300">
                     {typeof window !== 'undefined' && window.localStorage.getItem('runcard-watermark') === 'off' ? '' : 'Generated by RunCard Studio - runcard.studio'}
                   app/studio/components/PaceBandGenerator.tsx
                 app/studio/components/PaceBandGenerator.tsx
               )}
<div className="absolute bottom-2 right-2 text-[9px] font-mono text-text-muted bg-surface-lowest px-2 py-1 rounded border border-brand-border z-15 pointer-events-none opacity-40 uppercase tracking-widest font-bold">
             Scale: {(scale * 100).toFixed(0)}%
          app/studio/components/PaceBandGenerator.tsx
        app/studio/components/PaceBandGenerator.tsx
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (
             <SharedTemplates template={template} formData={formData} componentName="PaceBandGenerator" extraData={{ splits: typeof calculateSplits === "function" ? calculateSplits() : undefined }} />
           )}
      app/studio/components/PaceBandGenerator.tsx
    app/studio/components/PaceBandGenerator.tsx
  );
}
`);

// 5. PersonalBestGenerator.tsx
rewriteTail('PersonalBestGenerator.tsx',
'<div className="mt-6 text-left text-[9px] font-mono tracking-widest text-gray-400 uppercase">{typeof window !== \'undefined\' && window.localStorage.getItem(\'runcard-watermark\') === \'off\' ? \'\' : \'RunCard Studio\'}app/studio/components/PaceBandGenerator.tsx',
`<div className="mt-6 text-left text-[9px] font-mono tracking-widest text-gray-400 uppercase">{typeof window !== 'undefined' && window.localStorage.getItem('runcard-watermark') === 'off' ? '' : 'RunCard Studio'}app/studio/components/PaceBandGenerator.tsx
                 </>
               )}
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (
             <SharedTemplates template={template} formData={formData} componentName="PersonalBestGenerator"  />
           )}
      app/studio/components/PaceBandGenerator.tsx
    app/studio/components/PaceBandGenerator.tsx
  );
}
`);
