const fs = require('fs');
const path = require('path');

const dir = 'app/studio/components/';
const files = fs.readdirSync(dir).filter(f => f.endsWith('.tsx')).map(f => path.join(dir, f));

files.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');

  // Replace various incarnations of the watermark
  content = content.replace(/>\s*RunCard Studio\s*</g, '>{typeof window !== \'undefined\' && window.localStorage.getItem(\'runcard-watermark\') === \'off\' ? \'\' : \'RunCard Studio\'}<');
  content = content.replace(/>\s*Generated by RunCard Studio\s*</g, '>{typeof window !== \'undefined\' && window.localStorage.getItem(\'runcard-watermark\') === \'off\' ? \'\' : \'Generated by RunCard Studio\'}<');
  content = content.replace(/Generated by RunCard Studio - runcard.studio \/\/ stable-mvp/g, '{typeof window !== \'undefined\' && window.localStorage.getItem(\'runcard-watermark\') === \'off\' ? \'\' : \'Generated by RunCard Studio - runcard.studio\'}');
  content = content.replace(/RunCard Studio \/\/ lockscreen scale/g, '{typeof window !== \'undefined\' && window.localStorage.getItem(\'runcard-watermark\') === \'off\' ? \'\' : \'RunCard Studio\'}');
  content = content.replace(/>\s*Manual plan only\. Not medical or nutrition advice\.<br\/>RunCard Studio\s*</g, '>{typeof window !== \'undefined\' && window.localStorage.getItem(\'runcard-watermark\') === \'off\' ? \'Manual plan only. Not medical or nutrition advice.\' : <>Manual plan only. Not medical or nutrition advice.<br/>RunCard Studio</>}<');

  fs.writeFileSync(file, content);
  console.log(`Processed ${file}`);
});
