const fs = require('fs');

const extractAndFix = (file, search, replace) => {
    let content = fs.readFileSync('app/studio/components/' + file, 'utf8');
    content = content.replace(search, replace);
    fs.writeFileSync('app/studio/components/' + file, content);
}

// 1. ChallengeCardGenerator.tsx
// There is an unexpected `</>` followed by `)}` at the very end of the file.
extractAndFix('ChallengeCardGenerator.tsx',
`                        <div className="font-bold text-[#secondary-lime] text-sm uppercase">{formData.reward}</div>
)}
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (
             <SharedTemplates template={template} formData={formData} componentName="ChallengeCardGenerator"  />
           )}
</>               )}
            </div>
          </div>
        </div>`,
`                        <div className="font-bold text-[#secondary-lime] text-sm uppercase">{formData.reward}</div>
                      </div>
                   </>
               )}
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (
             <SharedTemplates template={template} formData={formData} componentName="ChallengeCardGenerator"  />
           )}
            </div>
          </div>
        </div>`);

// 2. FuelingPlanGenerator.tsx
extractAndFix('FuelingPlanGenerator.tsx',
`           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (
             <SharedTemplates template={template} formData={formData} componentName="FuelingPlanGenerator"  />
           )}
                 </div>               )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}`,
`                 </>
               )}
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (
             <SharedTemplates template={template} formData={formData} componentName="FuelingPlanGenerator"  />
           )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}`);

// 3. GoalCardGenerator.tsx
extractAndFix('GoalCardGenerator.tsx',
`                                   </div>
)}
                 </>
               )}

               {template === 'minimal goal' && (`,
`                                   </div>
                       )}
                     </div>
                 </>
               )}

               {template === 'minimal goal' && (`);

// 4. PaceBandGenerator.tsx
extractAndFix('PaceBandGenerator.tsx',
`                   <div className="mt-16 text-center text-[10px] font-mono uppercase tracking-[0.2em] opacity-40 pt-6 border-t border-dashed border-gray-300">
                     {typeof window !== 'undefined' && window.localStorage.getItem('runcard-watermark') === 'off' ? '' : 'Generated by RunCard Studio - runcard.studio'}
                   </div>
)}
<div className="absolute bottom-2 right-2 text-[9px] font-mono text-text-muted bg-surface-lowest px-2 py-1 rounded border border-brand-border z-15 pointer-events-none opacity-40 uppercase tracking-widest font-bold">
             Scale: {(scale * 100).toFixed(0)}%
          </div>
        </div>
</div>
)}
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (`,
`                   <div className="mt-16 text-center text-[10px] font-mono uppercase tracking-[0.2em] opacity-40 pt-6 border-t border-dashed border-gray-300">
                     {typeof window !== 'undefined' && window.localStorage.getItem('runcard-watermark') === 'off' ? '' : 'Generated by RunCard Studio - runcard.studio'}
                   </div>
                 </div>
               )}
<div className="absolute bottom-2 right-2 text-[9px] font-mono text-text-muted bg-surface-lowest px-2 py-1 rounded border border-brand-border z-15 pointer-events-none opacity-40 uppercase tracking-widest font-bold">
             Scale: {(scale * 100).toFixed(0)}%
          </div>
        </div>
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (`);

// 5. PersonalBestGenerator.tsx
extractAndFix('PersonalBestGenerator.tsx',
`                   {formData.feeling && (
                     <div className="mt-8 bg-gray-50 p-4 border-l-4 border-black text-sm font-serif italic text-gray-800">
                        &quot;{formData.feeling}&quot;
 </div>
 )}
<div className="mt-6 text-left text-[9px] font-mono tracking-widest text-gray-400 uppercase">{typeof window !== 'undefined' && window.localStorage.getItem('runcard-watermark') === 'off' ? '' : 'RunCard Studio'}</div>
)}
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (
             <SharedTemplates template={template} formData={formData} componentName="PersonalBestGenerator"  />
           )}
      </div>
    </div>
  );
}`,
`                   {formData.feeling && (
                     <div className="mt-8 bg-gray-50 p-4 border-l-4 border-black text-sm font-serif italic text-gray-800">
                        &quot;{formData.feeling}&quot;
                     </div>
                   )}
                   <div className="mt-6 text-left text-[9px] font-mono tracking-widest text-gray-400 uppercase">{typeof window !== 'undefined' && window.localStorage.getItem('runcard-watermark') === 'off' ? '' : 'RunCard Studio'}</div>
                 </div>
               )}
           {['carbon grid', 'race poster pro', 'minimal white', 'split panel', 'neon edge', 'print utility', 'compact story'].includes(template) && (
             <SharedTemplates template={template} formData={formData} componentName="PersonalBestGenerator"  />
           )}
      </div>
    </div>
  );
}`);

